import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Agora vai",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt">
			<body className="bg-gray-500 text-gray-400 text-9xl ">{children}</body>
		</html>
	);
}
